# -*- coding: utf-8 -*-
"""Tarsylia.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f3onDPF8yjnWPUN-NFrfOXuL_JYXwrcf
"""

from bs4 import BeautifulSoup
import urllib.request

url = 'http://www.tarsylia.com/tales-of-tarsylia-chapter-33-ta/'
page = urllib.request.urlopen(url)
soup = BeautifulSoup(page,features="html.parser")

def is_next(tag):
  try:
    return tag['rel']==["next"]
  except:
    return False

def get_next_page_url(soup):
  tag = soup.find(is_next)
  return(tag['href'])

search_depth = 181
for i in range(search_depth):
  try:
    img_src = soup.img['src']
    name = img_src.split('/')[-1]
    print(name)
    urllib.request.urlretrieve(img_src,'content/book4/'+name)
    next_url = get_next_page_url(soup)
    page = urllib.request.urlopen(next_url)
    soup = BeautifulSoup(page,features="html.parser")
  except:
    print(next_url)
    next_url = get_next_page_url(soup)
    page = urllib.request.urlopen(next_url)
    soup = BeautifulSoup(page,features="html.parser")